backend:
  name: git-gateway

  
media_folder: "img"
public_folder: "img"


collections: # A list of collections the CMS should be able to edit
  - name: "events" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "New Events" # Used in the UI, ie.: "New Post"
    folder: "_events" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "layout", name: "layout", widget: "hidden", default: "event", required: true}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Price", name: "price", widget: "number", required: true}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
